package io.provenance.classification.asset.verifier.config

enum class VerifierEventType {
    STREAM_EXCEPTION,
    STREAM_COMPLETED,
    NEW_BLOCK_RECEIVED,
    STREAM_RESTARTED,
    STREAM_EXITED,
    NEW_BLOCK_HEIGHT_RECEIVED,
    EVENT_IGNORED_UNKNOWN_WASM_EVENT,
    EVENT_IGNORED_NO_VERIFIER_ADDRESS,
    EVENT_IGNORED_UNHANDLED_EVENT_TYPE,
    EVENT_IGNORED_DIFFERENT_VERIFIER_ADDRESS,
    VERIFIER_ERROR_UNKNOWN_EVENT,
    ONBOARD_IGNORED_MISSING_SCOPE_ADDRESS,
    ONBOARD_IGNORED_PREVIOUSLY_PROCESSED,
    
}
